//anime:
export const FETCH_ANIME_REQUEST = "FETCH_ANIME_REQUEST";
export const FETCH_ANIME_SUCCESS = "FETCH_ANIME_SUCCESS";
export const FETCH_ANIME_FAILURE = "FETCH_ANIME_FAILURE";
//friends:
export const FETCH_FRIEND_REQUEST = "FETCH_FRIEND_REQUEST";
export const FETCH_FRIEND_SUCCESS = "FETCH_FRIEND_SUCCESS";
export const FETCH_FRIEND_FAILURE = "FETCH_FRIEND_FAILURE";
export const ADD_FRIEND_REQUEST = "ADD_FRIEND_REQUEST";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_FAILURE = "ADD_FRIEND_FAILURE";
export const REMOVE_FRIEND_REQUEST = "REMOVE_FRIEND_REQUEST";
export const REMOVE_FRIEND_SUCCESS = "REMOVE_FRIEND_SUCCESS";
export const REMOVE_FRIEND_FAILURE = "REMOVE_FRIEND_FAILURE";
export const FETCH_FRIEND_REQUESTS_SUCCESS = "FETCH_FRIEND_REQUESTS_SUCCESS";
export const FETCH_FRIEND_REQUESTS_FAILURE = "FETCH_FRIEND_REQUESTS_FAILURE";
